SATANIC = [
    'satan',
    'hatred',
    '666',
    'blackness',
    'blood',
    'rivers of blood',
    'fire',
    'pain',
    'wheel of pain',
    'burned alive',
    'eternity',
    'desecrated souls',
    'hopeless',
    'lightbringer',
    'unending torture',
    'darkness eternal',
    'cloven feet',
    'pitchfork',
    'infinite abyss',
    'nine circles',
    'natas',
    'circling demons',
    'Old Nick cometh',
    'black mass',
    'Lucifer',
    'Beelzebub',
    'chief of demons',
    'bow before the deceiver',
    'devourer of souls',
    'lies', 'deceiver',
    'Abbadon',
    'dark prince',
    'Morningstar',
    'pit of snakes',
    'drinking blood',
    'undying agony',
    'suffering',
    'everlasting fire',
    'torment unending',
    'inferno',
    'place of the condemned',
    'forever punished',
    'excruciating flame',
    'agonizing',
    'bottomless pit of the damned',
    'indulgence aplenty',
    'abase yourself before the defiler',
    'vengeance',
    'the great dragon awaits',
    'chains of gloomy darkness',
    'mighty voices of vengeance',
    'messenger of doom',
    'Shehamforash'
]

ENOCHIAN = [
    'casarem ohorela',
    'caba Pire',
    'zodomeda',
    'Micama! goho Pe-IAD!',
    'vaomesareji elonusa',
    'vaunalahe',
    'panupire',
    'cocasabe fafenu',
    'dasata ca-pi-mali cahisa',
    'elonusahinu cahisa',
    'Conisabera od auauotza tonuji oresa',
    'qurelesata',
    'oucaho sayomepe',
    'yorepoila tiobela busadire',
    'adoianu',
    'gohulime',
    'od fifisa balzodizodarasa',
    'Vanucahi omepetilabe oresa!',
    'Tonu paomebeda dizodalamo',
    'iadanamada',
    'Noco Mada, hoathahe Saitan',
    'od cicale Qaa',
    'noasa ta qu-a-nis',
    'ipezodi',
    'oeli meapeme',
    'cahisa'
]